# See https://pre-commit.com/ for usage and config
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.6.0]
        types: [python]
        exclude: setup.py

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [python]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        args: [--markdown-linebreak-ext=md]
        language: python
        types: [text]
    #-   id: end-of-file-fixer
    -   id: check-docstring-first
    #-   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: check-case-conflict

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: []

- repo: https://github.com/econchick/interrogate
  rev: 1.1.4  # or master if you're bold
  hooks:
  - id: interrogate
    args: [--quiet, --fail-under=85]
